### ISSUE TITLE
Unhandled exceptions not being reported to Sentry

### ISSUE THREAD

**Issue by mbajur** [krystal/apia#16]
Hello!

I was recently playing around with Apia for one of my production apps and stumbled upon a case in which my code raised an unhandled exception. Even though everything from Apia perspective worked as expected - i realized the exception was not re-risen after being catched by Apia therefore my exception catcher (Sentry) didn't created a report for it.

I can ofcourse wrap my every endpoint in 

```
begin
  code
rescue => e
  Sentry.capture(e)
  raise e
end
```

but i was wondering if there is maybe any better way of dealing with that globally? Like defining an unhandled error handler or something like that. Thanks!

**Comment by jimeh** [comment]
I'm afraid it's not well documented yet, but you can use the [`exception_handler`](https://www.rubydoc.info/gems/apia/3.5.1/Apia/DSLs/API#exception_handler-instance_method) API DSL method to perform custom handling of all errors within an API.

Something like this should do the trick:

```ruby
module CoreAPI
  class Base < Apia::API
    # ...

    exception_handler do |exception|
      Sentry.capture_exception(exception)
    end

    # ...
  end
end
```

**Comment by mbajur** [comment]
Ah, i will give this a go, thank you! And also - thank you for maintaining this amazing piece of software, i really wish it gets more popular among ruby folks and i will keep my fingers crossed for it 🤞
