### ISSUE TITLE
How to generate schema.json ?

### ISSUE THREAD

**Issue by mbajur** [krystal/apia#20]
Hello! I'm trying to generate a documentation for my API but i can't seem to find a way to generate the schema.json file mentioned in the apia-docs-generator docs. Could you help me with that? :) I don't think that is mentioned anywhere in the docs.

**Comment by mbajur** [comment]
Ok, i found a schema method in the codebase. Here is my rake task i used to generate the actual file if anyone needs it:

```
namespace :apia do
  task schema_dump: :environment do
    schema = V1Api::Base.schema(host: 'test.pl', namespace: 'v1')
    File.write(Rails.root.join('api_schema.json'), JSON.dump(schema))
  end
end
```

Or else, one can mount schema in his own api using 

```
class Base < Apia::API
  routes do
    schema
  end
end
```

and access it under `your_api_path/schema`

**Comment by jimeh** [comment]
Yep, we have similar rake tasks in a few of our apps.

There's also a couple of schema related add-on gems you may find interesting if you haven't seen them already:

- [apia-insomnia](https://github.com/krystal/apia-insomnia) — Generates a Insomnia request collection.
- [apia-openapi](https://github.com/krystal/apia-openapi) — Very experimental implementation of a OpenAPI scheme exporter for Apia.
